// The curated icon set: outlined Lucide icons (ISC licence). Import icons from
// '@medlearn/ui/icons' and render them with <Icon>; importing lucide-react directly is a lint
// error. Add an icon here when a screen needs it, so the set stays deliberate.
export {
  Activity,
  ArrowRight,
  BookMarked,
  BookOpen,
  Brain,
  CalendarDays,
  Check,
  ChevronLeft,
  ChevronRight,
  CircleAlert,
  CircleCheck,
  ClipboardCheck,
  Clock,
  Droplet,
  Dumbbell,
  ExternalLink,
  Eye,
  EyeOff,
  FileText,
  Flag,
  GraduationCap,
  Hourglass,
  House,
  Inbox,
  Info,
  Layers,
  Library,
  LoaderCircle,
  Menu,
  Monitor,
  Moon,
  Mountain,
  PenLine,
  PersonStanding,
  RefreshCw,
  Rotate3d,
  RotateCcw,
  Search,
  SlidersHorizontal,
  Stethoscope,
  Sun,
  Sunrise,
  Target,
  Trash2,
  TriangleAlert,
  Undo2,
  User,
  WifiOff,
  X,
} from 'lucide-react';
