// `pnpm db:types`: regenerates packages/db/src/database.types.ts from the local database.
// The output is checked before the file is replaced, so a failed run never leaves a broken
// or empty types file behind (a plain `> file` redirect empties the file before running).
import { writeFileSync } from 'node:fs';

import { capture, fail, step } from './lib/cli.mjs';

const TARGET = 'packages/db/src/database.types.ts';
const HEADER = '// Generated by `pnpm db:types` from the local database. Do not edit by hand.\n\n';

step('Generating database types from the local database');
const output = capture('pnpm', ['exec', 'supabase', 'gen', 'types', 'typescript', '--local']);

if (!output.includes('export type Database')) {
  fail(`Unexpected generator output; ${TARGET} was left unchanged:\n${output.slice(0, 500)}`);
}

writeFileSync(TARGET, HEADER + output.slice(output.indexOf('export type')));
console.log(`  wrote ${TARGET}`);
